name: Build & Release

on:
  push:
    tags:
      - 'v*' # Push events matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Build & Release
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            CMD_BUILD: pyinstaller --noconsole --noconfirm --clean --add-data icons:icons --add-data initial_worlds.json:. --exclude-module _bz2 --exclude-module _ctypes --exclude-module _decimal --exclude-module _hashlib --exclude-module _lzma --hidden-import wx._xml wxpymoo.py
            CMD_VERIFY: dir dist/wxpymoo
            CMD_PREZIP: echo
            FILE_NAME: wxpymoo-${{ github.ref_name }}_windows.zip
          - os: macos-12
            CMD_BUILD:  pyinstaller --onedir --windowed --noconsole --strip --noconfirm --clean --add-data icons:icons --add-data initial_worlds.json:. --exclude-module _bz2 --exclude-module _ctypes --exclude-module _decimal --exclude-module _hashlib --exclude-module _lzma --exclude-module numpy --hidden-import wx._xml wxpymoo.py
            CMD_VERIFY: ls -la dist/wxpymoo.app
            CMD_PREZIP: rm -rf dist/wxpymoo
            FILE_NAME: wxpymoo-${{ github.ref_name }}_macos.zip
          - os: ubuntu-latest
            CMD_BUILD: pyinstaller --noconsole --noconfirm --clean --strip --add-data icons:icons --add-data initial_worlds.json:. --exclude-module _bz2 --exclude-module _ctypes --exclude-module _decimal --exclude-module _hashlib --exclude-module _lzma --hidden-import wx._xml wxpymoo.py
            CMD_VERIFY: ls -la dist/wxpymoo
            FILE_NAME: wxpymoo-${{ github.ref_name }}_linux.zip

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Tools & Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-20.04 wxPython --user
          pip install pyinstaller==6.7.0 -r requirements.txt

      - name: Create Executable
        run: |
          echo "${{ github.ref_name }}" > version.txt
          ${{ matrix.CMD_BUILD }}

      - name: Create Zip Archive
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          directory: './dist'
          command: '${{ matrix.CMD_PREZIP }}'
          filename: '${{ matrix.FILE_NAME }}'

      - name: Verify Files
        run: |
          ${{ matrix.CMD_VERIFY }}

      - name: Upload Release Asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/${{ matrix.FILE_NAME }}
          asset_name: ${{ matrix.FILE_NAME }}
          tag: ${{ github.ref }}
          overwrite: true
          release_name: "wxpymoo ${{ github.ref_name }}"
          body: "${{ github.event.head_commit.message }}"
